### ISSUE TITLE
Stash pop fails if Gemfile.lock is changed on dev branch

### ISSUE THREAD

**Issue by wioux** [rubytune/perf_check#10]
When `rails s` gets run on the master branch, Gemfile.lock is regenerated, and if it differs from the version on the dev branch then `git stash pop` will bail.

```
Git stash applying...
error: Your local changes to the following files would be overwritten by merge:
    Gemfile.lock
Please, commit your changes or stash them before you can merge.
Aborting
```

**Comment by Manfred** [comment]
Fixed by installing the bundle with `--frozen` so it never updates the lock file.
