### ISSUE TITLE
Switch to experimental branch when running --deployment

### ISSUE THREAD

**Issue by Manfred** [rubytune/perf_check#46]
In the previous situation (i.e. using `perf_check_daemon`) we would always start `perf_check` in the ‘current branch’. This meant we never had to change branches at the start of the run. So:

Basically there are three relevant branches when running Perf Check:

1. The current branch
2. The reference branch (zero measurement for comparison)
3. The experimental branch

* As a user I want to automatically switch to the experimental branch when it's not the current branch when running in deployment mode.
* As a user I want to automatically switch back the current branch at the end of the experiment when running in deployment mode.

**Comment by sudara** [comment]
Would naming these `test_branch` vs. `reference_branch` help? Or should we stick to `branch` vs. `reference` where `branch` is implicitly the thing we care about testing.

**Comment by Manfred** [comment]
Maybe internally:

* `start_branch` for the branch at time 0:00
* `experimental_branch` for the branch that needs to be tested
* `baseline_branch` for the branch that is the baseline for the diff, we could also keep the name `reference_branch`.

And externally maybe one of these? I don't think the current naming is bad, but because it didn't work as expected it was a bit confusing.

```
perf_check --branch mst/performance  --against sudara/performance
perf_check --subject mst/performance  --baseline sudara/performance
perf_check --branch mst/performance  --reference sudara/performance
```

**Comment by sudara** [comment]
+1 to keeping `--reference` in both CLI and internally, as well as keeping `--branch` in the CLI.

My vote is `test_branch` or `experiment_branch` (as a noun) vs. `experimental_branch` internally. `experimental_branch` sounds less noun-y and more active somehow...

**Comment by Manfred** [comment]
Yes, I've decided that I'm not changing anything to the CLI options because they are obviously already as you want them. If you do want to change anything, please create an issue for that.

I'm not sure I follow your suggestion for internal naming. To me `test_branch` sounds like an imperative, like: TEST THAT BRANCH NOW! While `experimental_branch` is more descriptive.

**Comment by sudara** [comment]
> they are obviously already as you want them.

😁 Hopefully I haven't agitated you too much about naming today. It's true that I like to be careful with names and in existing projects like this, they usually have survived multiple people agreeing or disagreeing that they make sense. Also, it's a public API in active use this point, so we need to discuss whether it's worth it to deprecate/warn users if we want to change popular options.

> TEST THAT BRANCH NOW!

We were always so-so about `test_branch` just because `test` is so ambiguous. I do like `experiment` as it pairs nicely as a noun with both `reference`/`baseline`.

**Comment by Manfred** [comment]
> Also, it's a public API in active use this point

We can implement changes in a backwards compatible way where appropriate. I think it's worth choosing clear names and interfaces.

**Comment by sudara** [comment]
In that case I’m happy to migrate to experiment and baseline if you prefer em!

**Comment by Manfred** [comment]
PerfCheck now properly switches branches when in deployment mode. Closing this issue.
